# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 23:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_nav_menus', '0002_auto_20161216_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenu',
            name='menu',
            field=wagtail.wagtailcore.fields.StreamField((('nav_category', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('sub_nav', wagtail.wagtailcore.blocks.StreamBlock((('page_link', wagtail.wagtailcore.blocks.StructBlock((('override_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('open_in_new_tab', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))), ('external_link', wagtail.wagtailcore.blocks.StructBlock((('override_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('open_in_new_tab', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock())))), ('django_url', wagtail.wagtailcore.blocks.StructBlock((('override_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('open_in_new_tab', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('url_name', wagtail.wagtailcore.blocks.CharBlock())))), ('relative_url', wagtail.wagtailcore.blocks.StructBlock((('override_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('open_in_new_tab', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('link', wagtail.wagtailcore.blocks.RegexBlock(error_mesage={'invalid': 'Not a relative URL'}, regex='^(?!www\\.|(?:http|ftp)s?://|[A-Za-z]:\\\\|//).*'))))), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()))))))), ('page_link', wagtail.wagtailcore.blocks.StructBlock((('override_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('open_in_new_tab', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))), ('external_link', wagtail.wagtailcore.blocks.StructBlock((('override_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('open_in_new_tab', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock())))), ('django_url', wagtail.wagtailcore.blocks.StructBlock((('override_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('open_in_new_tab', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('url_name', wagtail.wagtailcore.blocks.CharBlock())))), ('relative_url', wagtail.wagtailcore.blocks.StructBlock((('override_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('open_in_new_tab', wagtail.wagtailcore.blocks.BooleanBlock(required=False)), ('link', wagtail.wagtailcore.blocks.RegexBlock(error_mesage={'invalid': 'Not a relative URL'}, regex='^(?!www\\.|(?:http|ftp)s?://|[A-Za-z]:\\\\|//).*'))))), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()))),
        ),
    ]
